# Generated by Django 3.0.5 on 2020-04-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_notes', '0003_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subtitle',
            field=models.CharField(default='Default Subtitle', max_length=200),
        ),
    ]
